[package]
name = "ipfs"
version = "0.1.0"
authors = ["Nick Hamann <nick@wabbo.org>"]

[dependencies]
atomicwrites = "0.0"
libc = "0.2"
openssl = "0.7"
rust-multihash = { git = "https://github.com/nham/rust-multihash.git" }
rustc-serialize = "0.3"
